module.exports = {
  "WEB_PORT": 8080,
  "ID_LENGTH": 5,
  "WEB_URL": "http://archbox:8080",
  "PW_SALT": "The salty salt",
  "TOKEN_SALT": "The super salty salt",
  "REGISTER_KEY": "test",
  "FILE_EXTENTION_CHECK": true,
  "MAX_SIZE": 100,
  "ALLOWED_EXTENTION": [
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".mp4",
    ".mp3",
    ".webm",
    ".txt",
    ".json",
    ".js",
    ".css",
    ".scss",
    ".bash",
    ".tar.gz",
    ".zip",
    ".gz",
    ".html",
    ".svg",
    ".gpg",
    ".tar.xz",
    ".php",
    "",
    ".pptx",
    ".docx",
    ".pdf",
    ".ptx"
  ]
}
